### ISSUE TITLE
/lib/httparty/hash_conversions.rb:35:in `normalize_param': warning: URI.escape is obsolete

### ISSUE THREAD

**Issue by mrjcleaver** [jnunemaker/httparty#281]
Since a recent install, I'm seeing hundreds of lines re: httparty URI.escape. I call via the soundcloud gem which calls httparty

The offending line is https://github.com/jnunemaker/httparty/blob/master/lib/httparty/hash_conversions.rb#L35

```
/var/lib/gems/1.9.1/gems/httparty-0.11.0/lib/httparty/hash_conversions.rb:35:in `normalize_param': warning: URI.escape is obsolete
/var/lib/gems/1.9.1/gems/httparty-0.11.0/lib/httparty/hash_conversions.rb:35:in `normalize_param': warning: URI.escape is obsolete
/var/lib/gems/1.9.1/gems/httparty-0.11.0/lib/httparty/hash_conversions.rb:35:in `normalize_param': warning: URI.escape is obsolete
/var/lib/gems/1.9.1/gems/httparty-0.11.0/lib/httparty/hash_conversions.rb:35:in `normalize_param': warning: URI.escape is obsolete
```

Should we remove the obsolete call?

**Comment by Olgagr** [comment]
I also see this warnings. HashConversions module still uses URI.encode.

**Comment by rusikf** [comment]
@Olgagr , @howdoicomputer, @the-robear , @jnunemaker  URI.encode was fixed in current master( not on release version) and this issue must be closed.

**Comment by mrjcleaver** [comment]
Any plan to release then? It's been another month and a half. Not fixed in 0.13.3.

**Comment by mrjcleaver** [comment]
Sorry to pester, but https://rubygems.org/gems/httparty still shows 0.13.3

![httparty 2015-03-11 09-09-54](https://cloud.githubusercontent.com/assets/59202/6596866/a650a398-c7ce-11e4-8ecb-35d28480131b.png)
